name: newa
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1


 
environment:
  sdk: ">=2.12.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^14.0.0  # A known stable version
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  device_info_plus: ^11.3.3
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.10
  permission_handler: ^11.4.0


  provider: ^6.1.1
  google_fonts: ^4.0.4
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  rive: ^0.13.0
  animated_text_kit: ^4.2.2
  http: ^1.3.0
  glassmorphism: ^3.0.0
  local_auth: ^2.1.7
  lottie: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  simple_animations: ^5.0.2
  supercharged: ^2.1.1
  email_validator: ^2.1.17
  fluttertoast: ^8.2.4
  sliver_tools: ^0.2.12
  custom_progress_button: ^2.0.1
  url_launcher: ^6.2.2
  flutter_easyloading: ^3.0.5
  connectivity_plus: ^5.0.2
  flutter_slidable: ^3.0.1
  animations: ^2.0.11
  flutter_rating_bar: ^4.0.1

  google_sign_in: ^6.1.6
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.5.2
  flutter_animate: ^4.5.2
  intl: ^0.17.0
  flutter_svg: ^2.0.9
  flutter_map: ^8.1.0
  latlong2: ^0.9.1
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.3
  maplibre_gl: ^0.21.0
  flutter_background_service: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/empty_menu.json
    - assets/animations/fingerprint.json
    - assets/animations/anime.json
    - assets/animations/login_animation.json
    - assets/icons/
    - assets/images/placeholder.png
    - assets/google_logo.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
